import Head from 'next/head';
import { useFetch } from '../hooks/useFetch';

interface RepositoryProps {
  full_name: string;
  description: string;
}
export default function Home() {
  const { data: repositories, isFetching } = useFetch<RepositoryProps[]>(
    'users/albertconceicao/repos'
  );

  return (
    <div>
      <Head>
        <title>Practicing API | Developer.Albert</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
        <section>
          {isFetching && <p>Carregando...</p>}
          {repositories?.map(repository => (
            <div className="repository" key={repository.full_name}>
              <small>Repositório</small>
              <h1>{repository.full_name}</h1>
              <p>{repository.description}</p>
            </div>
          ))}
        </section>
      </main>
    </div>
  );
}
